alias g git
alias ga "git add"
alias gap "git add -p"
alias gau "git add -u"
alias gb "git branch"
alias gbD "git branch -D"
alias gbd "git branch -d"
alias gc "git commit"
alias gca "git commit -a"
alias gcaa "git commit -a --amend"
alias gcam "git commit -am"
alias gch "git checkout"
alias gchb "git checkout -b"
alias gchm "git checkout main"
alias gcm "git commit -m"
alias gd "git diff"
alias gdc "git diff --cached"
alias gf "git fetch"
alias gfo "git fetch origin"
alias gfu "git fetch upstream"
alias gl "git log"
alias glG "git log -G"
alias glo "git log --oneline"
alias gm "git merge"
alias gpul "git pull"
alias gpulo "git pull origin"
alias gpulu "git pull upstream"
alias gpus "git push"
alias gpusf "git push --force-with-lease"
alias gpusu "git push -u"
alias gpusuo "git push -u origin"
alias gr "git rebase"
alias gri "git rebase -i"
alias grm "git remote"
alias grp "git rev-parse"
alias gs "git status"
alias gsh "git show"
alias gsp "git stash pop"
alias gst "git stash"
alias gsu "git submodule update"
alias gsui "git submodule update --init"
alias gsuir "git submodule update --init --recursive"
alias gsw "git switch"
alias gswc "git switch -c"
