local keymap = vim.keymap.set

-- reload without exiting vim
keymap('n', '<leader>rl', '<cmd>source ~/.config/nvim/init.lua<cr>')

-- 0.12 Native Undo Tree
keymap('n', '<leader>u', '<cmd>UndoTreeToggle<cr>', { desc = 'Toggle Native Undo Tree' })

-- Harpoon 2
keymap('n', '<leader>a', function()
    require('harpoon'):list():add()
end, { desc = 'Harpoon Add' })
keymap('n', '<C-e>', function()
    local h = require('harpoon')
    h.ui:toggle_quick_menu(h:list())
end, { desc = 'Harpoon List' })

-- Persistence
keymap('n', '<leader>ps', function()
    require('persistence').load()
end, { desc = 'Restore Session' })
keymap('n', '<leader>pS', function()
    require('persistence').select()
end, { desc = 'Select Session' })
keymap('n', '<leader>pl', function()
    require('persistence').load { last = true }
end, { desc = 'Restore Last Session' })
keymap('n', '<leader>pd', function()
    require('persistence').stop()
end, { desc = "Don't Save Current Session" })

-- Terminal Navigation (Adaptive for Tmux Navigator)
keymap('n', '<C-h>', '<cmd>TmuxNavigateLeft<cr>')
keymap('n', '<C-j>', '<cmd>TmuxNavigateDown<cr>')
keymap('n', '<C-k>', '<cmd>TmuxNavigateUp<cr>')
keymap('n', '<C-l>', '<cmd>TmuxNavigateRight<cr>')

-- Dotfile Management
keymap('n', '<leader>cz', function()
    require('chezmoi.pick').telescope()
end, { desc = 'Chezmoi' })

-- Explicit Formatting
keymap('', '<leader>f', function()
    require('conform').format { async = true }
end)

-- Bufferline Navigation
keymap('n', '<S-h>', '<cmd>BufferLineCyclePrev<cr>', { desc = 'Prev Buffer' })
keymap('n', '<S-l>', '<cmd>BufferLineCycleNext<cr>', { desc = 'Next Buffer' })
keymap('n', '[b', '<cmd>BufferLineCyclePrev<cr>', { desc = 'Prev Buffer' })
keymap('n', ']b', '<cmd>BufferLineCycleNext<cr>', { desc = 'Next Buffer' })
keymap('n', '[B', '<cmd>BufferLineMovePrev<cr>', { desc = 'Move buffer prev' })
keymap('n', ']B', '<cmd>BufferLineMoveNext<cr>', { desc = 'Move buffer next' })

-- Bufferline Actions
keymap('n', '<leader>bp', '<Cmd>BufferLineTogglePin<CR>', { desc = 'Toggle Pin' })
keymap('n', '<leader>bP', '<Cmd>BufferLineGroupClose ungrouped<CR>', { desc = 'Delete Non-Pinned Buffers' })
keymap('n', '<leader>br', '<Cmd>BufferLineCloseRight<CR>', { desc = 'Delete Buffers to the Right' })
keymap('n', '<leader>bl', '<Cmd>BufferLineCloseLeft<CR>', { desc = 'Delete Buffers to the Left' })
keymap('n', '<leader>bj', '<cmd>BufferLinePick<cr>', { desc = 'Pick Buffer' })

-- LSP hover
local function show_documentation()
    local filetype = vim.bo.filetype
    if filetype == "vim" or filetype == "help" then
        vim.cmd('h ' .. vim.fn.expand('<cword>'))
    elseif filetype == "man" then
        vim.cmd('Man ' .. vim.fn.expand('<cword>'))
    elseif vim.fn.expand('%:t') == 'Cargo.toml' and require('crates').popup_available() then
        require('crates').show_popup()
    else
        vim.lsp.buf.hover { border = 'rounded' }
    end
end

keymap('n', 'K', show_documentation, { desc = 'LSP Hover' })

-- 1. Format File (Native LSP - works for Go, Rust, Python, etc.)
keymap('n', '<leader>cf', function()
    vim.lsp.buf.format { async = true }
end, { desc = 'Format File' })

-- 2. Organize Imports (Specifically optimized for Ruff/Pyright)
keymap('n', '<leader>co', function()
    vim.lsp.buf.code_action {
        context = { only = { 'source.organizeImports' }, diagnostics = {} },
        apply = true,
    }
end, { desc = 'Organize Imports' })

-- Top Pickers & Explorer
keymap('n', '<leader><space>', function()
    Snacks.picker.smart()
end, { desc = 'Smart Find Files' })
keymap('n', '<leader>,', function()
    Snacks.picker.buffers()
end, { desc = 'Buffers' })
keymap('n', '<leader>/', function()
    Snacks.picker.grep()
end, { desc = 'Grep' })
keymap('n', '<leader>:', function()
    Snacks.picker.command_history()
end, { desc = 'Command History' })
keymap('n', '<leader>n', function()
    Snacks.picker.notifications()
end, { desc = 'Notification History' })
keymap('n', '<leader>e', function()
    Snacks.explorer()
end, { desc = 'File Explorer' })

-- find
keymap('n', '<leader>fb', function()
    Snacks.picker.buffers()
end, { desc = 'Buffers' })
keymap('n', '<leader>fc', function()
    Snacks.picker.files { cwd = vim.fn.stdpath('config') }
end, { desc = 'Find Config File' })
keymap('n', '<leader>ff', function()
    Snacks.picker.files()
end, { desc = 'Find Files' })
keymap('n', '<leader>fg', function()
    Snacks.picker.git_files()
end, { desc = 'Find Git Files' })
keymap('n', '<leader>fp', function()
    Snacks.picker.projects()
end, { desc = 'Projects' })
keymap('n', '<leader>fr', function()
    Snacks.picker.recent()
end, { desc = 'Recent' })

-- git
keymap('n', '<leader>gb', function()
    Snacks.picker.git_branches()
end, { desc = 'Git Branches' })
keymap('n', '<leader>gl', function()
    Snacks.picker.git_log()
end, { desc = 'Git Log' })
keymap('n', '<leader>gL', function()
    Snacks.picker.git_log_line()
end, { desc = 'Git Log Line' })
keymap('n', '<leader>gs', function()
    Snacks.picker.git_status()
end, { desc = 'Git Status' })
keymap('n', '<leader>gS', function()
    Snacks.picker.git_stash()
end, { desc = 'Git Stash' })
keymap('n', '<leader>gd', function()
    Snacks.picker.git_diff()
end, { desc = 'Git Diff (Hunks)' })
keymap('n', '<leader>gf', function()
    Snacks.picker.git_log_file()
end, { desc = 'Git Log File' })

-- gh
keymap('n', '<leader>gi', function()
    Snacks.picker.gh_issue()
end, { desc = 'GitHub Issues (open)' })
keymap('n', '<leader>gI', function()
    Snacks.picker.gh_issue { state = 'all' }
end, { desc = 'GitHub Issues (all)' })
keymap('n', '<leader>gp', function()
    Snacks.picker.gh_pr()
end, { desc = 'GitHub Pull Requests (open)' })
keymap('n', '<leader>gP', function()
    Snacks.picker.gh_pr { state = 'all' }
end, { desc = 'GitHub Pull Requests (all)' })

-- Grep
keymap('n', '<leader>sb', function()
    Snacks.picker.lines()
end, { desc = 'Buffer Lines' })
keymap('n', '<leader>sB', function()
    Snacks.picker.grep_buffers()
end, { desc = 'Grep Open Buffers' })
keymap('n', '<leader>sg', function()
    Snacks.picker.grep()
end, { desc = 'Grep' })
keymap({ 'n', 'x' }, '<leader>sw', function()
    Snacks.picker.grep_word()
end, { desc = 'Visual selection or word' })

-- search
keymap('n', '<leader>s"', function()
    Snacks.picker.registers()
end, { desc = 'Registers' })
keymap('n', '<leader>s/', function()
    Snacks.picker.search_history()
end, { desc = 'Search History' })
keymap('n', '<leader>sa', function()
    Snacks.picker.autocmds()
end, { desc = 'Autocmds' })
keymap('n', '<leader>sb', function()
    Snacks.picker.lines()
end, { desc = 'Buffer Lines' })
keymap('n', '<leader>sc', function()
    Snacks.picker.command_history()
end, { desc = 'Command History' })
keymap('n', '<leader>sC', function()
    Snacks.picker.commands()
end, { desc = 'Commands' })
keymap('n', '<leader>sd', function()
    Snacks.picker.diagnostics()
end, { desc = 'Diagnostics' })
keymap('n', '<leader>sD', function()
    Snacks.picker.diagnostics_buffer()
end, { desc = 'Buffer Diagnostics' })
keymap('n', '<leader>sh', function()
    Snacks.picker.help()
end, { desc = 'Help Pages' })
keymap('n', '<leader>sH', function()
    Snacks.picker.highlights()
end, { desc = 'Highlights' })
keymap('n', '<leader>si', function()
    Snacks.picker.icons()
end, { desc = 'Icons' })
keymap('n', '<leader>sj', function()
    Snacks.picker.jumps()
end, { desc = 'Jumps' })
keymap('n', '<leader>sk', function()
    Snacks.picker.keymaps()
end, { desc = 'Keymaps' })
keymap('n', '<leader>sl', function()
    Snacks.picker.loclist()
end, { desc = 'Location List' })
keymap('n', '<leader>sm', function()
    Snacks.picker.marks()
end, { desc = 'Marks' })
keymap('n', '<leader>sM', function()
    Snacks.picker.man()
end, { desc = 'Man Pages' })
keymap('n', '<leader>sp', function()
    Snacks.picker.lazy()
end, { desc = 'Search for Plugin Spec' })
keymap('n', '<leader>sq', function()
    Snacks.picker.qflist()
end, { desc = 'Quickfix List' })
keymap('n', '<leader>sR', function()
    Snacks.picker.resume()
end, { desc = 'Resume' })
keymap('n', '<leader>su', function()
    Snacks.picker.undo()
end, { desc = 'Undo History' })
keymap('n', '<leader>uC', function()
    Snacks.picker.colorschemes()
end, { desc = 'Colorschemes' })

-- LSP
keymap('n', 'gd', function()
    Snacks.picker.lsp_definitions()
end, { desc = 'Goto Definition' })
keymap('n', 'gD', function()
    Snacks.picker.lsp_declarations()
end, { desc = 'Goto Declaration' })
keymap('n', 'gr', function()
    Snacks.picker.lsp_references()
end, { desc = 'References', nowait = true })
keymap('n', 'gI', function()
    Snacks.picker.lsp_implementations()
end, { desc = 'Goto Implementation' })
keymap('n', 'gy', function()
    Snacks.picker.lsp_type_definitions()
end, { desc = 'Goto T[y]pe Definition' })
keymap('n', 'gai', function()
    Snacks.picker.lsp_incoming_calls()
end, { desc = 'C[a]lls Incoming' })
keymap('n', 'gao', function()
    Snacks.picker.lsp_outgoing_calls()
end, { desc = 'C[a]lls Outgoing' })
keymap('n', '<leader>ss', function()
    Snacks.picker.lsp_symbols()
end, { desc = 'LSP Symbols' })
keymap('n', '<leader>sS', function()
    Snacks.picker.lsp_workspace_symbols()
end, { desc = 'LSP Workspace Symbols' })

-- Other
keymap('n', '<leader>z', function()
    Snacks.zen()
end, { desc = 'Toggle Zen Mode' })
keymap('n', '<leader>Z', function()
    Snacks.zen.zoom()
end, { desc = 'Toggle Zoom' })
keymap('n', '<leader>.', function()
    Snacks.scratch()
end, { desc = 'Toggle Scratch Buffer' })
keymap('n', '<leader>S', function()
    Snacks.scratch.select()
end, { desc = 'Select Scratch Buffer' })
keymap('n', '<leader>n', function()
    Snacks.notifier.show_history()
end, { desc = 'Notification History' })
keymap('n', '<leader>bd', function()
    Snacks.bufdelete()
end, { desc = 'Delete Buffer' })
keymap('n', '<leader>cR', function()
    Snacks.rename.rename_file()
end, { desc = 'Rename File' })
keymap({ 'n', 'v' }, '<leader>gB', function()
    Snacks.gitbrowse()
end, { desc = 'Git Browse' })
keymap('n', '<leader>gg', function()
    Snacks.lazygit()
end, { desc = 'Lazygit' })
keymap('n', '<leader>un', function()
    Snacks.notifier.hide()
end, { desc = 'Dismiss All Notifications' })
keymap({ 'n', 't' }, ']]', function()
    Snacks.words.jump(vim.v.count1)
end, { desc = 'Next Reference' })
keymap({ 'n', 't' }, '[[', function()
    Snacks.words.jump(-vim.v.count1)
end, { desc = 'Prev Reference' })
